# Nombre del pipeline
name: CI

# Trigger on push
on:
  push:

# Jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Hola mundo
        run: |
          echo "hola mundo"
      - name: Hola mundo 2
        run: |
          echo "Echo número 2"
